-- TechLink Phase 2 — public guestbook
-- Run this in Supabase SQL Editor.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 40),
  professional text not null default 'General'
    check (professional in ('General','Wilan','Arman','Sherlyn','Madelain')),
  message text not null check (char_length(trim(message)) between 1 and 500),
  reply text,
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages(created_at);
create index if not exists messages_professional_idx on public.messages(professional);

-- The API uses the server-side Supabase service-role key.
-- Keep RLS enabled and do not expose the service-role key in frontend code.
alter table public.messages enable row level security;
